[project]
name = "comfyui-easelhub-nodes"
version = "1.0.0"
description = "High-performance, lightweight nodes for ComfyUI by EaselHub"
readme = "README.md"
license = { file = "LICENSE" }
dependencies = ["torch", "numpy", "opencv-python"]

[tool.comfy]
PublisherId = "easelhub"
DisplayName = "EaselHub Nodes"
Icon = ""
